name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up dependencies
        run: sudo apt install -y g++ make libbrotli1 libbrotli-dev

      - name: Build project
        run: make
